name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    needs: build
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publish
      run: dotnet nuget push ./dist/ -k ${{secrets.NUGET_API_KEY}}
